baseURL = "https://mikectobias.com"
languageCode = "en-us"
title = "Mike Tobias"

# theme = "github.com/nodejh/hugo-theme-mini"

theme = "keepit"
enableEmoji = true
enableRobotsTXT = true

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Blog"
    url = "/posts"
    weight = 2

  # [[menu.main]]
  #   name = "About"
  #   url = "/about"
  #   weight = 3

  # [[menu.main]]
  #   name = "Categories"
  #   url = "/categories/"
  #   weight = 4


[params]
    since = 2019
    author = "Mike Tobias"               # Author's name
    title = "Software Engineer - "
    titleLogo = "/images/bitcoinira-logo.png"
    titleLink = "https://bitcoinira.com/"
    subtitle = "C#, Typescript, Go, Golf, Zen, Coffee"       # Subtitle
    cdn_url = ""           # Base CDN URL
    home_mode = "" # post or other

    google_verification = ""
    bing_verification = ""
    yandex_verification = ""
    pinterest_verification = ""
    baidu_verification = ""
    
    avatar = "/images/me/avatar.jpg" #comment it to use gravatar
    socialShare = true
    
    description = "Technology, Software, and Life" # site description
    keywords = "technology, software, development, life, learning, education, blogging, coding, javascript, react, c#, .net, network, security" # site keywords

    license= 'Released under <a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

[params.gravatar]
    #email = "example@gmail.com"   #uncomment and insert your email address to use gravatar


[params.social]
    Email   = "mike.c.tobias@gmail.com"
    GitHub = "https://github.com/mct-dev"
    Linkedin = "https://www.linkedin.com/in/mikectobias/"
    Strava = "3304364"
    Twitter = "https://twitter.com/mctdev"
    Keybase = "npchampion"
    Goodreads = "61629997-mike-tobias"
    #Instagram = "xxxx"
    #Facebook = "xxxx"
    #Telegram = "xxxx"
    #Medium = "xxxx"
    #Gitlab = "xxxx"
    #Youtubelegacy = "xxxx"
    #Youtubecustom = "xxxx"
    #Youtubechannel = "xxxx"
    #Tumblr ="xxxx"
    #Quora = "xxxx"
    #Pinterest = "xxxx"
    #Reddit = "xxxx"
    #Codepen = "xxxx"
    #Bitbucket = "xxxx"
    #Stackoverflow = "xxxxx"
    #Weibo = "xxxx"
    #Odnoklassniki = "xxxx"
    #VKontakte = "xxxx"
    #Flickr = "xxxx"
    #Xing = "xxxx"
    #Snapchat = "xxxx"
    #Soundcloud = "xxxx"
    #Spotify = "xxxx"
    #Bandcamp = "xxxx"
    #Paypal = "xxxx"
    #Fivehundredpx = "xxxx"
    #Mix = "xxxx"
    #Lastfm = "xxxx"
    #Foursquare = "xxxx"
    #Hackernews = "xxxx"
    #Kickstarter = "xxxx"
    #Patreon = "xxxx"
    #Steam = "xxxx"
    #Twitch = "xxxx"
    #Skype = "xxxx"
    #Whatsapp = "xxxx"
    #Zhihu = "xxxx"
    #Douban = "xxxx"
    #Angellist = "xxxx"
    #Slidershare = "xxxx"
    #Jsfiddle = "xxxx"
    #Deviantart = "xxxx"
    #Behance = "xxxx"
    #Dribble = "xxxx"
    #Wordpress = "xxxx"
    #Vine = "xxxx"
    #Googlescholar = "xxxx"
    #Researchgate = "xxxx"
    #Mastodon = "xxxx"
    #Thingiverse = "xxxx"

[params.share]
Twitter = true
HackerNews = true
Facebook = true
Reddit = true
Linkedin = true
#Pinterest = true
#Mix = true
Tumblr = true
#VKontakte = true
#Douban = true
#Weibo = true

# Used only for Seo schema 
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."

[author]
  name = "Mike Tobias"

  [params.publisher]
    name = "Mike Tobias"

    [params.publisher.logo]
      url = "logo.png"
      width = 127
      height = 40

  [params.logo]
    url = "logo.png"
    width = 127
    height = 40

  [params.image]
    url = "cover.png"
    width = 800
    height = 600

[params.gitalk]           
owner = ""              
repo = ""               
clientId = ""           
clientSecret = ""   
